# Generated by Django 4.2.15 on 2024-08-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='citu',
            new_name='city',
        ),
    ]
